name: solana_pay
description: "Make payment with Solana Crypto "
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  twilio_flutter: ^0.9.0
  supabase_flutter: ^2.8.0
  solana: ^0.31.0
  just_audio: ^0.9.41
  qr_flutter: ^4.1.0
  saver_gallery: ^3.0.6
  device_info_plus: ^11.0.0
  dio: ^5.7.0
  permission_handler: ^11.3.1
  share_plus: ^10.0.3
  rive: ^0.13.14
  mobile_scanner: ^6.0.1
  
  flutter_native_splash: ^2.4.1
  pinput: ^5.0.0
  pin_code_fields: ^8.0.1
  lottie: ^3.1.2
  rename_app: ^1.6.1
  

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/log.png"
  adaptive_icon_background: "#ffffff"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/B.png
  android: true
  ios: true
  android_12:
    color: "#ffffff"
    image: assets/B.png


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icon/
    - assets/1.png
    - assets/2.png
    - assets/3.png
  

