// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbZO3sOpEcDUNGZ8ZCMiKRJRH-fv4ILUM',
    appId: '1:373062513057:web:a0435a11aba89a83da9be0',
    messagingSenderId: '373062513057',
    projectId: 'solana-bdff5',
    authDomain: 'solana-bdff5.firebaseapp.com',
    storageBucket: 'solana-bdff5.appspot.com',
    measurementId: 'G-H2X602HQ56',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVznysFnp4ASEefAcPYRYEysSpcb7bmo4',
    appId: '1:373062513057:android:fd87aa5de98e1b49da9be0',
    messagingSenderId: '373062513057',
    projectId: 'solana-bdff5',
    storageBucket: 'solana-bdff5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAxrO1NWL4QZZZNVdw4OrvM1AOOqLX4Sg',
    appId: '1:373062513057:ios:88f48665993689dfda9be0',
    messagingSenderId: '373062513057',
    projectId: 'solana-bdff5',
    storageBucket: 'solana-bdff5.appspot.com',
    iosBundleId: 'com.example.solanaPay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAxrO1NWL4QZZZNVdw4OrvM1AOOqLX4Sg',
    appId: '1:373062513057:ios:88f48665993689dfda9be0',
    messagingSenderId: '373062513057',
    projectId: 'solana-bdff5',
    storageBucket: 'solana-bdff5.appspot.com',
    iosBundleId: 'com.example.solanaPay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbZO3sOpEcDUNGZ8ZCMiKRJRH-fv4ILUM',
    appId: '1:373062513057:web:ca7bcea2c4a754f7da9be0',
    messagingSenderId: '373062513057',
    projectId: 'solana-bdff5',
    authDomain: 'solana-bdff5.firebaseapp.com',
    storageBucket: 'solana-bdff5.appspot.com',
    measurementId: 'G-6QVSRZ446P',
  );
}
